# Generated by Django 5.0.6 on 2026-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('critical', 'Critical')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('days_since_login', models.IntegerField(default=0)),
                ('orders_last_7_days', models.IntegerField(default=0)),
                ('payment_failures', models.IntegerField(default=0)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'churn_predictions',
            },
        ),
        migrations.CreateModel(
            name='RevenueForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_revenue_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_lower', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_upper', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_used', models.CharField(default='moving_average', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'revenue_forecasts',
            },
        ),
    ]
