# Generated by Django 5.0.6 on 2026-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundry', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('order_received', 'Order Received'), ('status_washing', 'Status: Washing'), ('status_drying', 'Status: Drying'), ('status_ironing', 'Status: Ironing'), ('order_ready', 'Order Ready for Pickup'), ('pickup_reminder_24h', 'Pickup Reminder (24h overdue)'), ('pickup_reminder_48h', 'Pickup Reminder (48h overdue)'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed - Retry'), ('rent_due_7d', 'Rent Due in 7 Days'), ('rent_due_today', 'Rent Due Today')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('template_text', models.TextField(help_text='Use {{customer_name}}, {{order_number}}, {{status}}, {{total}}, {{shop_name}} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('trigger', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('cost_kes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
