# Generated by Django 5.0.6 on 2026-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rent_due_soon', 'Rent Due Soon'), ('rent_overdue', 'Rent Overdue'), ('reserve_low', 'Reserve Low'), ('reserve_safe', 'Reserve Safe'), ('projection_critical', 'Projection Critical')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'rent_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent_kes', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('due_day_of_month', models.IntegerField(default=5)),
                ('is_auto_reserve', models.BooleanField(default=True)),
                ('auto_reserve_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('reserve_amount_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('projected_month_end_kes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('projection_confidence', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('critical', 'Critical')], default='safe', max_length=10)),
                ('last_projected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'rent_reserves',
            },
        ),
    ]
