# Generated by Django 5.0.6 on 2026-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('stripe', 'Stripe')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('initiated', 'STK Push Initiated'), ('pending', 'Awaiting Customer'), ('processing', 'Callback Received'), ('completed', 'Payment Successful'), ('failed', 'Failed / Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=15)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=2)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('rent_reserve_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laundry.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_callback', models.JSONField()),
                ('result_code', models.IntegerField(null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('orphaned', 'Orphaned'), ('reconciled', 'Reconciled')], default='received', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
            options={
                'db_table': 'payment_logs',
            },
        ),
    ]
